### ISSUE TITLE
free text fields in Open311_ServiceRequest

### ISSUE THREAD

**Issue by ilarimikkonen** [smart-data-models/dataModel.IssueTracking#6]
Hi,

https://fiware-datamodels.readthedocs.io/en/latest/IssueTracking/Open311_ServiceRequest/doc/spec/index.html specifies that `Applications must use the types Text`

Text allows also >< etc and this is a problem with Orion: https://fiware-orion.readthedocs.io/en/1.4.0/user/forbidden_characters/index.html

Any suggestion how to reconcile this difference?

**Comment by albertoabellagarcia** [comment]
sorry for the simple answer, use all Text chars but those forbidden? 
anyhow I am forwarding this question to platform people for further insights if necessary.
