### ISSUE TITLE
Missmatch beetween swagger and examples

### ISSUE THREAD

**Issue by sromerotech** [smart-data-models/dataModel.IssueTracking#7]
I've been checking the models and they seem to be not in sync. For example, the [swagger](https://swagger.lab.fiware.org/?url=https://smart-data-models.github.io/dataModel.IssueTracking/Open311_ServiceRequest/swagger.yaml) definition doesn't mention the property `attributes`, which it's in the [NGSI-V2](https://smart-data-models.github.io/dataModel.IssueTracking/Open311_ServiceRequest/examples/example.json) example. Other missing attribute is `address_string`, being `address` in the swagger definition the only attribute that looks like it.

**Comment by albertoabellagarcia** [comment]
Thanks, you're right there are some mismatches. We'll correct them.
Thanks for noticing. I am not closing the issue till we fix it.

**Comment by albertoabellagarcia** [comment]
Fixed. Thanks for noticing.
